title: My CFD Portfolio
description: CFD projects engineered for accuracy and performance.
author: "Kamil Dylewicz"

theme: minima

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%d-%m-%Y"

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/projects.md

include:
    - _pages

# Minima social links
github_username: dylewiczk
linkedin_username: kamil-dylewicz-5a2984170